# Generated by Django 2.1.7 on 2019-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='static/default/default_avatar.png', upload_to='media/uploads/%Y/%m/%d', verbose_name="User's Avatar"),
        ),
    ]
