# Generated by Django 2.1.7 on 2019-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20190508_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name="Answers's Dislikes"),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0, verbose_name="Answers's Likes"),
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name="Question's Dislikes"),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name="Question's Likes"),
        ),
        migrations.AlterField(
            model_name='likedislikequestion',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Vote'),
        ),
    ]
