# Generated by Django 2.1.7 on 2019-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20190508_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_number',
            field=models.IntegerField(default=0, verbose_name="Answer's Number"),
        ),
    ]
